# This is a basic workflow to help you get started with Actions

name: Lint code

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"

      - name: Install project dependencies
        run: poetry install --with web-backend,dev

      - name: Run precommit hooks
        run: poetry run pre-commit run --all-files
