name: Push tag, create image, release

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve version from pyproject.toml
        id: version
        run: echo "VERSION=$(grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)" >> $GITHUB_ENV

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          # ternary operation to choose tag input based on how this workflow was triggered
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true